use_frameworks!

platform :ios, '9.0'

target 'HZChartViews_Example' do
  pod 'HZChartViews', :path => '../'

  target 'HZChartViews_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
